# OpenRouter API key for LLM completions
# Replace with your actual API key
OPENROUTER_API_KEY = "your-openrouter-api-key"

# Logo.dev API token for company logos
# Replace with your actual Logo.dev token
LOGO_DEV_TOKEN = "pk_S8c9XqxWSbKr5qN8VUWAOg"
